name: quran_flutter
description: A multilingual Quran application, free for everyone as Sadakah Jariyah.
publish_to: 'none'
version: 1.0.0+4

environment:
  sdk: ^3.12.2

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_local_notifications: ^22.3.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^10.3.1
  flutter_timezone: ^5.1.0
  http: ^1.6.0
  quran_library:
    path: vendor/quran_library
  shared_preferences: ^2.5.5
  timezone: ^0.11.1
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/fonts/OFL-NotoSansBengali.txt
  fonts:
    - family: NotoSansBengali
      fonts:
        - asset: assets/fonts/NotoSansBengali.ttf
